[workspace]

members = [
    "common",
    "phase1_commitment",
    "phase2_policy",
    "phase3_registry",
    "registry_generator",
    "phase4_orchestrator",
    "beta22_test",
]

default-member = "phase4_orchestrator"
