# --------------------------
# Doctor 1
# --------------------------
doctor1_id = "5001"
doctor1_pubkey_x = "1111"
doctor1_pubkey_y = "2222"

# --------------------------
# Doctor 2
# --------------------------
doctor2_id = "5002"
doctor2_pubkey_x = "3333"
doctor2_pubkey_y = "4444"

# --------------------------
# Doctor 3
# --------------------------
doctor3_id = "5003"
doctor3_pubkey_x = "5555"
doctor3_pubkey_y = "6666"

# --------------------------
# Doctor 4
# --------------------------
doctor4_id = "5004"
doctor4_pubkey_x = "7777"
doctor4_pubkey_y = "8888"

# --------------------------
# Authentication Path Target
# --------------------------
doctor_index = "0"
